//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CouncilMembers
    {
        public int id { get; set; }
        public Nullable<int> Member_Id { get; set; }
        public Nullable<int> Role_Id { get; set; }
        public Nullable<int> Council_id { get; set; }
    }
}
