//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NcDemo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NeighborhoodCouncilEntities : DbContext
    {
        public NeighborhoodCouncilEntities()
            : base("name=NeighborhoodCouncilEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Announcement_Info> Announcement_Info { get; set; }
        public virtual DbSet<Announcements> Announcements { get; set; }
        public virtual DbSet<Candidates> Candidates { get; set; }
        public virtual DbSet<Council> Council { get; set; }
        public virtual DbSet<CouncilMembers> CouncilMembers { get; set; }
        public virtual DbSet<Elections> Elections { get; set; }
        public virtual DbSet<Meeting_Minutes> Meeting_Minutes { get; set; }
        public virtual DbSet<Meetings> Meetings { get; set; }
        public virtual DbSet<Member> Member { get; set; }
        public virtual DbSet<Nomination> Nomination { get; set; }
        public virtual DbSet<Notifications> Notifications { get; set; }
        public virtual DbSet<Panel> Panel { get; set; }
        public virtual DbSet<PanelMembers> PanelMembers { get; set; }
        public virtual DbSet<Problems_History> Problems_History { get; set; }
        public virtual DbSet<Project_Logs> Project_Logs { get; set; }
        public virtual DbSet<Projects> Projects { get; set; }
        public virtual DbSet<Report_Problem> Report_Problem { get; set; }
        public virtual DbSet<Report_Problem_info> Report_Problem_info { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Serve> Serve { get; set; }
        public virtual DbSet<Votes> Votes { get; set; }
    }
}
