//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monthly_Contributions
    {
        public int id { get; set; }
        public Nullable<int> council_id { get; set; }
        public Nullable<int> member_id { get; set; }
        public string month_year { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
