//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notifications
    {
        public int id { get; set; }
        public int council_id { get; set; }
        public Nullable<int> member_id { get; set; }
        public string module { get; set; }
        public string title { get; set; }
        public string message { get; set; }
        public string action_url { get; set; }
        public string data { get; set; }
        public Nullable<bool> is_read { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
