//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_Likes
    {
        public int id { get; set; }
        public int project_id { get; set; }
        public int member_id { get; set; }
        public bool like_status { get; set; }
        public Nullable<System.DateTime> like_date { get; set; }
    }
}
