//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_Problem_info
    {
        public int id { get; set; }
        public int Report_Problem_id { get; set; }
        public int Member_id { get; set; }
        public int Council_id { get; set; }
    }
}
