//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NcDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Votes
    {
        public int id { get; set; }
        public Nullable<int> Voter_id { get; set; }
        public Nullable<int> Candidate_id { get; set; }
        public Nullable<int> Election_id { get; set; }
        public Nullable<System.DateTime> Vote_date { get; set; }
    }
}
